"""Add fitness survey fields to User model

Revision ID: 48a566688e17
Revises: 
Create Date: 2025-04-24 20:31:37.863813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a566688e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitness_experience', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('workout_time', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dietary_preferences', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fitness_challenges', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fitness_challenges')
        batch_op.drop_column('dietary_preferences')
        batch_op.drop_column('workout_time')
        batch_op.drop_column('fitness_experience')

    # ### end Alembic commands ###
